#!/bin/bash
# Quick reference for wasmi-daisy usage

echo "═══════════════════════════════════════════════════════"
echo "  wasmi-daisy - WebAssembly for Daisy Seed"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "📦 Library Info:"
echo "  Location: $(pwd)/target/thumbv7em-none-eabihf/release/libwasmi_daisy.a"
echo "  Size: $(ls -lh target/thumbv7em-none-eabihf/release/libwasmi_daisy.a 2>/dev/null | awk '{print $5}' || echo 'Not built')"
echo "  Header: $(pwd)/wasmi_daisy.h"
echo ""
echo "🔨 Commands:"
echo "  Build:    ./build.sh"
echo "  Rebuild:  cargo clean && ./build.sh"
echo "  Check:    cargo check --release"
echo ""
echo "📚 Documentation:"
echo "  README.md       - Library overview"
echo "  INTEGRATION.md  - How to integrate with Daisy"
echo "  SUCCESS.md      - Build details and architecture"
echo "  example.cpp     - Usage example"
echo ""
echo "🎯 Quick Integration:"
echo ""
echo "Add to your Daisy project Makefile:"
echo "  C_INCLUDES += -I$(pwd)"
echo "  LDFLAGS += $(pwd)/target/thumbv7em-none-eabihf/release/libwasmi_daisy.a"
echo ""
echo "Then in your C++ code:"
echo "  #include \"wasmi_daisy.h\""
echo ""
echo "═══════════════════════════════════════════════════════"
